"""added relationships

Revision ID: 0efd06a4136d
Revises: b764fa5e667e
Create Date: 2023-11-20 19:07:49.054019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efd06a4136d'
down_revision = 'b764fa5e667e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('book_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_loans_member_id_members'), 'members', ['member_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_loans_book_id_books'), 'books', ['book_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_loans_book_id_books'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_loans_member_id_members'), type_='foreignkey')
        batch_op.drop_column('book_id')
        batch_op.drop_column('member_id')

    # ### end Alembic commands ###
